### ISSUE TITLE
CUDA out of memory with 8.00GB

### ISSUE THREAD

**Issue by lzn1273180880** [PeterL1n/BackgroundMattingV2#174]
Hello! 大佬你们好！
I recieve an error when I tried to run the dataset of yours `b1.mp4`  and the error is RuntimeError:` CUDA out of memory. Tried to allocate 1.48 GiB (GPU 0; 8.00 GiB total capacity; 3.86 GiB already allocated; 628.69 MiB free; 5.68 GiB reserved in total by PyTorch)`.
Is my GPU memory insufficient? I supposed it would run with 8Gb of GPU MEM. Does it need more MEM?
Looking forward to your reply if you guys are free, thank you!

**Comment by lzn1273180880** [comment]
Now I've successfully run the program via output of `pha`, but another error ouccured like `IndexError: Idx: 389 out of length: 416
`, the video indeed has been ouput but the quality was not that good.
![image](https://user-images.githubusercontent.com/94612909/158015630-8b1cdb40-629c-4b94-9e1c-94f5968a8b10.png)
How can I avoid it?

**Comment by lzn1273180880** [comment]
problem solved, thank you.
